package fr.kensai.raven.defaults;

import com.kitfox.docking.DockingContent;
import com.kitfox.docking.DockingRegionRoot;

import java.awt.BorderLayout;

/**
 *
 * @author kitfox
 */
public class DockingTestFrame2 extends javax.swing.JFrame
{
    DockingRegionRoot dockPanel = new DockingRegionRoot();

    int index;

    /** Creates new form DockingTestFrame2 */
    public DockingTestFrame2()
    {
        initComponents();

        getContentPane().add(dockPanel, BorderLayout.CENTER);
        setSize(640, 480);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        cm_addTextPane = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_file.setText("File");

        cm_addTextPane.setText("Add text pane");
        cm_addTextPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm_addTextPaneActionPerformed(evt);
            }
        });
        menu_file.add(cm_addTextPane);

        jMenuBar1.add(menu_file);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cm_addTextPaneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cm_addTextPaneActionPerformed
    {//GEN-HEADEREND:event_cm_addTextPaneActionPerformed
        TestContentTextPane pane = new TestContentTextPane();
        DockingContent cont = new DockingContent(
                "uid" + index, "Component " + (index++), pane);
        dockPanel.getDockingRoot().addDockContent(cont);
    }//GEN-LAST:event_cm_addTextPaneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DockingTestFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cm_addTextPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_file;
    // End of variables declaration//GEN-END:variables

}
