package fr.kensai.raven.defaults;

import com.kitfox.docking.test2.DockingTabbedPanel;
import java.awt.BorderLayout;
import javax.swing.JButton;

/**
 *
 * @author kitfox
 */
public class DockingTestFrame extends javax.swing.JFrame
{
    DockingTabbedPanel panel = new DockingTabbedPanel();

    /** Creates new form DockingTestFrame */
    public DockingTestFrame()
    {
        initComponents();

        getContentPane().add(panel, BorderLayout.CENTER);

        panel.addPanel("alpha", new JButton("Alpha"));
        panel.addPanel("beta", new JButton("Beta"));
        panel.addPanel("gamma", new JButton("Gamma"));

        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DockingTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
